# Generated by Django 4.2.2 on 2023-06-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cleaning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Extra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Назва додаткової послуги"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Цiна додаткової послуги",
                    ),
                ),
                (
                    "price_description",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Префiкс цiни"
                    ),
                ),
            ],
            options={
                "verbose_name": "Додаткова послуга",
                "verbose_name_plural": "Додатковi послуги",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Послуга", "verbose_name_plural": "Послуги"},
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описання послуги"),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, verbose_name="Цiна послуги"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Назва послуги"),
        ),
    ]
