# Generated by Django 4.2.2 on 2023-06-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cleaning", "0002_extra_alter_service_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="price_description",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Префiкс цiни"
            ),
        ),
    ]
