# Generated by Django 4.2.2 on 2023-06-26 13:10

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cleaning", "0003_service_price_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="extra",
            name="icon_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name=models.CharField(
                    max_length=255, verbose_name="Назва додаткової послуги"
                ),
            ),
        ),
    ]
