# Generated by Django 4.2.2 on 2023-06-26 13:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cleaning", "0004_extra_icon_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extra",
            name="icon_image",
        ),
        migrations.AddField(
            model_name="service",
            name="icon_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="<django.db.models.fields.CharField>",
            ),
        ),
    ]
