# Generated by Django 4.2.2 on 2023-07-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cleaning", "0007_rename_icon_image_service_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="extra",
            name="type",
            field=models.TextField(
                choices=[("sofa", "Sofa"), ("other", "Other")],
                default="other",
                verbose_name="Тип",
            ),
        ),
    ]
