# Generated by Django 4.2.2 on 2023-08-16 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cleaning", "0008_extra_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extra",
            name="type",
        ),
    ]
