# Generated by Django 4.2.2 on 2023-09-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cleaning", "0009_remove_extra_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Назва посту")),
                ("text", models.TextField(verbose_name="Вмiст тексту поста")),
            ],
            options={
                "verbose_name": "Коментарiй",
                "verbose_name_plural": "Коментарi",
            },
        ),
    ]
