# Cleaning-service/api/Dockerfile
FROM python:3.10

WORKDIR /django

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Установка зависимостей
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y postgresql gcc python3-dev

RUN pip install --upgrade pip

# Копирование и установка Python зависимостей
COPY ./requirements.txt /django/
RUN pip install --no-cache-dir -r requirements.txt

# Копирование всего остального кода
COPY ./ /django/

# Делаем entrypoint.sh исполняемым
RUN chmod +x /django/entrypoint.sh
