# Этап сборки
FROM node:18.16.0 as build_one
WORKDIR /react
COPY package.json package-lock.json ./
RUN npm install
COPY . ./
RUN npm run build

# Этап запуска
FROM nginx:latest as serve
COPY --from=build_one /react/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
