# Этап сборки
FROM node:18-alpine as build_one
WORKDIR /react

COPY package.json package-lock.json ./

RUN npm install
COPY . ./
RUN node --max_old_space_size=4096 ./node_modules/.bin/react-scripts build
RUN npm run build

# Этап запуска
FROM nginx:latest as serve
COPY --from=build_one /react/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
